<div class="definition">
    <strong>Hacker</strong> [hack·er] /n/ - One who seeks to understand the details of a system and strives to stretch it's capabilities beyond the original intent.
</div>

<?php if ($this->meetingTonight): ?>
    <div class="alert alert-success">
        <strong>Meeting tonight starting at 6pm!</strong>
        Check the <a href="https://groups.google.com/forum/#!forum/phx2600">latest discussions</a> for more info.
    </div>
<?php elseif ($this->meetingThisFriday): ?>
    <div class="alert alert-info">
        <strong>Meeting this Friday, <?php echo date('F j, Y', $this->ff); ?>.</strong>
        Check the <a href="https://groups.google.com/forum/#!forum/phx2600">latest discussions</a> for more <info class=""></info>
    </div>
<?php endif; ?>

<div class="row">

    <div class="span8">

        <div id="next-meeting" class="well">
            <p>The next meeting witll be held at 6:00 PM on</p>

            <div class="clearfix">
                <div class="meeting-month">
                    <div class="number"><?php echo date('M', $this->ff); ?></div>
                    <div class="midLine"></div>
                </div>
                <div class="meeting-day">
                    <div class="number"><?php echo date('d', $this->ff); ?></div>
                    <div class="midLine"></div>
                </div>
                <div class="meeting-year">
                    <div class="number"><?php echo date('Y', $this->ff); ?></div>
                    <div class="midLine"></div>
                </div>
            </div>

            <p><i class="icon-map-marker"></i>  <a href="#mapModal" data-toggle="modal">Lux Central</a></p>

        </div>

    </div>

    <div id="forum-feed" class="span4 pull-right">

        <h4>Latest Discussion Topics <a href="http://goo.gl/97FG3" title="Subscribe to the PHX2600 topics feed" class="feed-icon pull-right"><i class="icon-rss"></i></a></h4>

        <div class="forum-feed-wrapper">

            <ul class="feed-list">
                <?php if ($this->forumFeed !== false): ?>

                    <?php $x = 1; foreach ($this->forumFeed as $item): ?>

                        <?php $date = new DateTime($item->updated()); ?>

                        <li class="<?php echo ($x % 2 == 0) ? 'even' : 'odd'; ?>">
                            <a href="<?php echo $item->link['href']; ?>">
                                <span class="feed-title"><?php echo $item->title(); ?></span>
                                <small><?php echo $item->author->name(); ?> on <?php echo date('M j, Y - g:i a', $date->getTimestamp()); ?></small>
                            </a>
                        </li>
                    <?php $x++; endforeach; ?>

               <?php else: ?>

                   <li>Error: Something went wrong with the feed</li>

               <?php endif; ?>
            </ul>

        </div>

    </div>

</div>

<div id="info-boxes" class="row">

    <div class="info-box span4">
        <h5>The Phoenix, Arizona Network of Hackers</h5>
        <p>The PHX2600 is a local group of hackers and technology enthusiasts that meet on a monthly
        basis to discuss all things code, tech or otherwise hacker related. Most members enjoy
        exploring and exploting technology and life in an effort to better use and understand those
        systems.</p>
    </div>

    <div class="info-box span4">
        <h5>Meeting Info</h5>
        <p>Meetings are held on the first Friday of every month starting at 6PM. There is rarely a
        planned schedule and anyone prepared to give a presentation or show off a
        project may do so at any time during the meeting. All meetings are open to the public.</p>

        <center><a href="/guidelines" clas="btn btn-link">View Meeting Guidelines</a></center>
    </div>

    <div class="info-box span4">
        <h5>News and Updates</h5>
        <p>Join the discussion on our Google Group or follow us on Twitter or Google+ for news, meeting reminders and more.</p>
        <center>
            <p>
                <a href="https://groups.google.com/forum/#!forum/phx2600" class="social-link groups" title="Join our Google Group">
                    <i class="icon-envelope"></i>
                </a>
                <a href="https://plus.google.com/117910250839532154362" class="social-link google" rel="publisher" title="Follow PHX2600 on Google+" >
                    <i class="icon-google-plus" ></i>
                </a>
                <a href="https://twitter.com/PHX2600"class="social-link twitter" title="Follow PHX2600 on Twitter">
                    <i class="icon-twitter"></i>
                </a>
            </p>
        </center>
    </div>

</div>

<div id="mapModal" class="modal fade hide">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>HeatSync Labs</h3>
    </div>
    <div class="modal-body">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3327.034658874291!2d-112.07622568481806!3d33.50047538075967!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872b12ecf6d5df1f%3A0x9c94e3196571aa51!2sLux+Central!5e0!3m2!1sen!2sus!4v1501216910878" width="530" height="360" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>
