<div class="row">
    
    <div class="span12">
        
        <h1 class="page-title">An error occurred</h1>
        <p><?php echo $this->message ?></p>
        
        <?php if (isset($this->exception)): ?>
            
            <div class="exception-info">
                <h3>Exception information:</h3>
                <p>
                    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
                </p>
                
                <h4>Stack trace:</h4>
                <pre><?php echo $this->exception->getTraceAsString() ?></pre>
                
                <h4>Request Parameters:</h4>
                <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
            </div>
            
        <?php endif ?>
        
    </div>
    
</div>